### ISSUE TITLE
Fix or remove Archim builder

### ISSUE THREAD

**Issue by thijstriemstra** [V1EngineeringInc/MarlinBuilder#141]
[For years](https://github.com/V1EngineeringInc/MarlinBuilder/commits/main) the ci build status of this project has been failed, solely because of the Archim board/architecture it seems. I would suggest to allow it to fail and not set the overall build status of the project to failed. Otherwise it seems this project will never have a proper ci build (at first glance that was my impression at least).

**Comment by V1EngineeringInc** [comment]
It only fails from the dual versions of the archim. That said, I almost took it out last week. I really don't mind taking it out. I will do it next time I make some changes, or if you want to do it sooner I will merge it.

https://github.com/V1EngineeringInc/MarlinBuilder/actions

**Comment by thijstriemstra** [comment]
Sounds good @V1EngineeringInc If you need someone to review that future PR, let me know and I'll take a look.
