### ISSUE TITLE
LCD Timout not working?

### ISSUE THREAD

**Issue by V1EngineeringInc** [V1EngineeringInc/MarlinBuilder#26]
Using the main branch, The LCD never returns to the main menu.

I have it set to 3 minutes, in the current main branch. Config_adv line 1095-6. At least on the mp3dp mini rambo version. I can try more boards a bit later this afternoon.

**Comment by V1EngineeringInc** [comment]
Works now?

**Comment by jeffeb3** [comment]
Did you change something? I didn't see a PR. I'm worried you made a change, but it didn't get into main for some reason.

**Comment by V1EngineeringInc** [comment]
No I narrowed it down. The timeout only works when it is not "printing". I assume that is a marlin bug. 

I just poured more coffee and was going to look into the main marlin PR's.

**Comment by V1EngineeringInc** [comment]
https://github.com/MarlinFirmware/Marlin/pull/17887

Only thing I am seeing, but don't understand it enough to know if this caused the issue. Or I am missing something. In config-adv there is a setting in the custom script menu,   //#define USER_SCRIPT_RETURN  // Return to status screen after a script, not sure if maybe this needs to be set since we user some custom scripts. The issue happens if I just start a print and adjust the temp, it never goes back to the status screen, so it is not just custom scripts.
