### ISSUE TITLE
Rambo board cnc dual is setup for dual z instead of dual x

### ISSUE THREAD

**Issue by mmerkel22** [V1EngineeringInc/MarlinBuilder#76]
I downloaded the Rambo dual cnc firmware on 3/31 and it compiled and loaded fine but I found that it was setup for dual y and z drivers. I changed it to dual x and y and the motion is fine now. Just wanted to let you know. Keep up the great work. Thanks.

**Comment by V1EngineeringInc** [comment]
If it had dualLR in the title that is for the Lowrider. Can you check your zip file name please.

**Comment by mmerkel22** [comment]
It was the V1_CNC_Dual

**Comment by jeffeb3** [comment]
Can you post the exact filename? I will gladly trace this issue, but the thing that makes the most sense is that you accidentally grabbed the LR version.

V1CNC_Ramps_Dual
is different than 
V1CNC_Ramsp_DualLR

**Comment by mmerkel22** [comment]
Yes you are correct. My bad. I downloaded both but opened the low rider in vs code.

**Comment by jeffeb3** [comment]
Thank you for checking.
