### ISSUE TITLE
V1CNC_Ramps_Dual-2.0.7.2-src is zipped twice

### ISSUE THREAD

**Issue by kselavko** [V1EngineeringInc/MarlinBuilder#77]
The V1CNC_Ramps_Dual-2.0.7.2-src zip folder has a separate zip folder inside of it (downloaded from https://github.com/V1EngineeringInc/MarlinBuilder/releases).  It would be nice if you only needed to unzip once.

**Comment by V1EngineeringInc** [comment]
You can use Xloader if you are not making edits and not need to unzip the large folder. Those instructions are soon to come.
